import { Bell, RotateCw } from 'lucide-react';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { api } from '../api/client';
import { useApp } from '../context/AppContext';
import type { Alert, Consultation, Recommendation } from '../types';
import { ActionButton, EmptyState, ExpertOnlyNote, FarmRequired, Field, LoadingState, Notice, PageHeader, RecommendationCard, SelectField, TextAreaField, WorkflowResult, apiError } from '../components/Ui';

export function PlanningPage() {
  const { farmId } = useApp(); const [result, setResult] = useState<Recommendation | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!farmId) return; const f = new FormData(e.currentTarget); const lat = f.get('lat'); const lng = f.get('lng'); const q: Record<string, unknown> = { field_ref: f.get('field_ref'), crop_name: f.get('crop_name'), lat: lat ? Number(lat) : undefined, lng: lng ? Number(lng) : undefined }; setBusy(true); setError(''); setResult(null); try { setResult(await api.planning(farmId, q)); } catch (x) { setError(apiError(x)); } finally { setBusy(false); } }
  return <div className="page-wrap"><PageHeader eyebrow="ANALYSIS / FIELD DECISION" title="Planting window" description="Combine the field and crop context with available soil, calendar, and optional location signals."/><div className="workflow-grid"><section className="panel"><span className="eyebrow">Planning context</span><h2>Assess a field</h2><FarmRequired/><form className="form-stack" onSubmit={submit}><Field name="field_ref" label="Field reference" required placeholder="e.g. North field"/><Field name="crop_name" label="Crop" required placeholder="e.g. tomato"/><div className="field-pair"><Field name="lat" label="Latitude (optional)" type="number" step="any"/><Field name="lng" label="Longitude (optional)" type="number" step="any"/></div><ActionButton type="submit" busy={busy} disabled={!farmId}>Review planting conditions</ActionButton></form></section><section className="workflow-output"><div className="eyebrow">Recommendation</div><WorkflowResult result={result} error={error} loading={busy} onRetry={() => document.querySelector<HTMLFormElement>('.workflow-grid form')?.requestSubmit()}/></section></div></div>;
}

export function MarketPage() {
  const { farmId } = useApp(); const [result, setResult] = useState<Recommendation | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!farmId) return; const f = new FormData(e.currentTarget); setBusy(true); setError(''); setResult(null); try { setResult(await api.market(farmId, String(f.get('crop_name')), String(f.get('market_name')))); } catch (x) { setError(apiError(x)); } finally { setBusy(false); } }
  return <div className="page-wrap"><PageHeader eyebrow="ANALYSIS / MARKET SIGNAL" title="Market intelligence" description="Request available market data. If the provider is unavailable, Aranya will report that directly."/><div className="workflow-grid"><section className="panel"><span className="eyebrow">Market watch</span><h2>What are you selling?</h2><FarmRequired/><form className="form-stack" onSubmit={submit}><Field name="crop_name" label="Crop" required placeholder="e.g. tomato"/><Field name="market_name" label="Market or mandi" required placeholder="e.g. Nashik APMC"/><ActionButton type="submit" busy={busy} disabled={!farmId}>Check market signal</ActionButton></form></section><section className="workflow-output"><div className="eyebrow">Market response</div><WorkflowResult result={result} error={error} loading={busy} onRetry={() => document.querySelector<HTMLFormElement>('.workflow-grid form')?.requestSubmit()}/></section></div></div>;
}

export function EconomicsPage() {
  const { farmId } = useApp(); const [result, setResult] = useState<Recommendation | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  async function submitRecord(e: FormEvent<HTMLFormElement>, kind: 'expense' | 'sale') { e.preventDefault(); if (!farmId) return; const form = e.currentTarget; const values = Object.fromEntries(new FormData(form).entries()); const context = Object.fromEntries(new FormData(document.getElementById('economics-query') as HTMLFormElement).entries()); if (!String(context.field_ref || '').trim() || !String(context.crop_name || '').trim()) { setError('Enter the field and current crop before recording a transaction.'); return; } const merged = { ...values, ...context }; const fields = kind === 'expense' ? { ...merged, amount: Number(values.amount) } : { ...merged, quantity_kg: Number(values.quantity_kg), price_per_kg: Number(values.price_per_kg) }; setBusy(true); setError(''); setNotice(''); try { const saved = kind === 'expense' ? await api.logExpense(farmId, fields) : await api.logSale(farmId, fields); setNotice(`${kind === 'expense' ? 'Expense' : 'Sale'} recorded (entry ${saved.id}).`); form.reset(); } catch (x) { setError(apiError(x)); } finally { setBusy(false); } }
  async function query(e?: FormEvent) { e?.preventDefault(); if (!farmId) return; const form = document.getElementById('economics-query') as HTMLFormElement; const values = new FormData(form); const field = String(values.get('field_ref') || '').trim(); const crop = String(values.get('crop_name') || '').trim(); if (!field || !crop) { setError('Enter a field and crop to calculate economics.'); return; } setBusy(true); setError(''); setNotice(''); setResult(null); try { setResult(await api.economics(farmId, field, crop)); } catch (x) { setError(apiError(x)); } finally { setBusy(false); } }
  async function cycle() { if (!farmId) return; const f = document.getElementById('economics-query') as HTMLFormElement; const values = new FormData(f); const field = String(values.get('field_ref') || '').trim(); const crop = String(values.get('crop_name') || '').trim(); if (!field || !crop) { setError('Enter the field and crop before starting a new cycle.'); return; } if (!window.confirm(`Start a new ${crop} cycle for ${field}? This ends the current cycle's tracking.`)) return; setBusy(true); setError(''); setNotice(''); try { const saved = await api.newCycle(farmId, field, crop); setResult(null); setNotice(`New crop cycle started (entry ${saved.id}).`); } catch (x) { setError(apiError(x)); } finally { setBusy(false); } }
  return <div className="page-wrap"><PageHeader eyebrow="ANALYSIS / FARM ECONOMICS" title="Field economics" description="Log this cycle’s transactions and ask Aranya to calculate the current field result."/><FarmRequired/><section className="panel economics-context"><span className="eyebrow">Shared field context</span><form id="economics-query" className="field-pair"><Field name="field_ref" label="Field reference" required placeholder="e.g. North field"/><Field name="crop_name" label="Current crop" required placeholder="e.g. tomato"/></form></section><div className="economics-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">Record costs</span><h2>Expense</h2></div></div><form className="form-stack" onSubmit={(e) => void submitRecord(e, 'expense')}><input type="hidden" name="field_ref"/><input type="hidden" name="crop_name"/><SelectField name="category" label="Category"><option value="seed">Seed</option><option value="fertilizer">Fertilizer</option><option value="labor">Labor</option><option value="irrigation">Irrigation</option><option value="pesticide">Pesticide</option><option value="other">Other</option></SelectField><Field name="amount" label="Amount (₹)" type="number" min="0.01" step="0.01" required/><ActionButton busy={busy} disabled={!farmId}>Save expense</ActionButton></form></section><section className="panel"><div className="panel-heading"><div><span className="eyebrow">Record harvest</span><h2>Sale</h2></div></div><form className="form-stack" onSubmit={(e) => void submitRecord(e, 'sale')}><input type="hidden" name="field_ref"/><input type="hidden" name="crop_name"/><Field name="quantity_kg" label="Quantity (kg)" type="number" min="0.01" step="any" required/><Field name="price_per_kg" label="Price per kg (₹)" type="number" min="0.01" step="any" required/><ActionButton busy={busy} disabled={!farmId}>Save sale</ActionButton></form></section></div><div className="inline-toolbar"><ActionButton onClick={() => void query()} busy={busy} disabled={!farmId}>Calculate field result</ActionButton><ActionButton variant="secondary" onClick={() => void cycle()} busy={busy} disabled={!farmId}><RotateCw size={15}/> Start new crop cycle</ActionButton></div>{notice && <Notice tone="success">{notice}</Notice>}{error && <Notice tone="error">{error}</Notice>}{result && <RecommendationCard recommendation={result}/>}</div>;
}

export function SchemesPage() {
  const { farmId } = useApp(); const [result, setResult] = useState<Recommendation | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!farmId) return; const f = new FormData(e.currentTarget); const query = { land_acres: f.get('land_acres') ? Number(f.get('land_acres')) : null, category: f.get('category') || null, crop_name: f.get('crop_name') || null }; if (!query.land_acres && !query.category) { setError('Enter land size or choose a farmer category.'); return; } setBusy(true); setError(''); setResult(null); try { setResult(await api.schemes(farmId, query)); } catch (x) { setError(apiError(x)); } finally { setBusy(false); } }
  return <div className="page-wrap"><PageHeader eyebrow="ACTION / ELIGIBILITY" title="Scheme matching" description="Compare your context with Aranya’s curated reference. Results are not a live government feed."/><div className="workflow-grid"><section className="panel"><span className="eyebrow">Eligibility context</span><h2>About the farm</h2><FarmRequired/><form className="form-stack" onSubmit={submit}><Field name="land_acres" label="Land size (acres)" type="number" min="0" step="any"/><SelectField name="category" label="Farmer category"><option value="">Select if applicable</option><option value="small">Small farmer</option><option value="marginal">Marginal farmer</option><option value="woman">Woman farmer</option><option value="sc">SC</option><option value="st">ST</option><option value="general">General</option></SelectField><Field name="crop_name" label="Crop (optional)"/><ActionButton type="submit" busy={busy} disabled={!farmId}>Match schemes</ActionButton></form></section><section className="workflow-output"><div className="eyebrow">Reference match</div><WorkflowResult result={result} error={error} loading={busy} onRetry={() => document.querySelector<HTMLFormElement>('.workflow-grid form')?.requestSubmit()}/></section></div></div>;
}

export function ResearchPage() {
  const { farmId } = useApp(); const [result, setResult] = useState<Recommendation | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!farmId) return; const f = new FormData(e.currentTarget); setBusy(true); setError(''); setResult(null); try { setResult(await api.research(farmId, String(f.get('query')), String(f.get('crop_name') || ''))); } catch (x) { setError(apiError(x)); } finally { setBusy(false); } }
  return <div className="page-wrap"><PageHeader eyebrow="INTELLIGENCE / RESEARCH" title="Explore a symptom" description="Search the existing curated knowledge base for a crop issue. Text is a weaker signal than a photo."/><div className="workflow-grid"><section className="panel"><span className="eyebrow">Describe the observation</span><h2>What are you noticing?</h2><FarmRequired/><form className="form-stack" onSubmit={submit}><TextAreaField name="query" label="Symptom or question" required placeholder="Describe the visible signs, where they appear, and when you noticed them."/><Field name="crop_name" label="Crop (optional)" placeholder="e.g. tomato"/><ActionButton type="submit" busy={busy} disabled={!farmId}>Search field knowledge</ActionButton></form></section><section className="workflow-output"><div className="eyebrow">Knowledge response</div><WorkflowResult result={result} error={error} loading={busy} onRetry={() => document.querySelector<HTMLFormElement>('.workflow-grid form')?.requestSubmit()}/></section></div></div>;
}

export function FieldHistoryPage() {
  const { farmId } = useApp(); const [data, setData] = useState<Awaited<ReturnType<typeof api.history>> | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!farmId) return; const f = new FormData(e.currentTarget); setBusy(true); setError(''); setData(null); try { setData(await api.history(farmId, String(f.get('field_ref')), String(f.get('crop_name')))); } catch (x) { setError(apiError(x)); } finally { setBusy(false); } }
  return <div className="page-wrap"><PageHeader eyebrow="ANALYSIS / FARM MEMORY" title="Field history" description="Retrieve what Aranya has recorded for a field. Only stored history is shown."/><div className="workflow-grid"><section className="panel"><span className="eyebrow">Look up a field</span><form className="form-stack" onSubmit={submit}><FarmRequired/><Field name="field_ref" label="Field reference" required/><Field name="crop_name" label="Crop" required/><ActionButton type="submit" busy={busy} disabled={!farmId}>Retrieve history</ActionButton></form></section><section className="workflow-output"><div className="eyebrow">Recorded observations</div>{busy ? <LoadingState label="Retrieving farm memory"/> : error ? <Notice tone="error">{error} <button className="inline-button" onClick={() => document.querySelector<HTMLFormElement>('.workflow-grid form')?.requestSubmit()}>Retry</button></Notice> : data ? data.scan_count ? <div className="panel history-panel"><span className="eyebrow">{data.field_ref} · {data.scan_count} record(s)</span><h2>{data.latest_status || 'Latest status unavailable'}</h2>{data.latest_affected_area_pct !== undefined && <p>Affected area: {data.latest_affected_area_pct}%</p>}{data.latest_timestamp && <p className="muted">Most recent: {data.latest_timestamp}</p>}</div> : <EmptyState title="No scans recorded" detail={data.message || 'No recorded observations were returned for this field.'}/> : <EmptyState title="No query yet" detail="Choose a field and crop to request stored observations."/>}</section></div></div>;
}

export function AlertsPage() {
  const { farmId } = useApp(); const [alerts, setAlerts] = useState<Alert[]>([]); const [consultations, setConsultations] = useState<Consultation[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [busyId, setBusyId] = useState<number | null>(null); const [message, setMessage] = useState('');
  const load = useCallback(async () => { if (!farmId) { setAlerts([]); setConsultations([]); return; } setLoading(true); setError(''); try { const [a, c] = await Promise.all([api.alerts(farmId), api.consultations(farmId)]); setAlerts(a); setConsultations(c); } catch (e) { setError(apiError(e)); } finally { setLoading(false); } }, [farmId]);
  useEffect(() => { void load(); }, [load]);
  async function acknowledge(id: number) { if (!farmId) return; setBusyId(id); setMessage(''); try { await api.acknowledge(farmId, id); setAlerts((items) => items.filter((item) => item.id !== id)); setMessage('Alert acknowledged.'); } catch (e) { setError(apiError(e)); } finally { setBusyId(null); } }
  async function resolve(e: FormEvent<HTMLFormElement>, id: number) { e.preventDefault(); if (!farmId) return; const values = Object.fromEntries(new FormData(e.currentTarget).entries()); setBusyId(id); setError(''); try { await api.resolveConsultation(farmId, id, String(values.expert_name), String(values.notes)); setMessage(`Consultation ${id} resolved.`); await load(); } catch (x) { setError(apiError(x)); } finally { setBusyId(null); } }
  return <div className="page-wrap"><PageHeader eyebrow="ACTION / PRIORITY QUEUE" title="Alerts & consultations" description="Review farm alerts and any cases currently waiting for expert follow-up." action={<ActionButton variant="secondary" onClick={() => void load()}><RotateCw size={15}/> Refresh</ActionButton>}/><FarmRequired/>{error && <Notice tone="error">{error}</Notice>}{message && <Notice tone="success">{message}</Notice>}{loading ? <LoadingState label="Loading alerts and consultations"/> : <><section className="queue-section"><div className="section-heading"><div><span className="eyebrow">FARM GUARDIAN</span><h2>Active alerts <span className="count-badge">{alerts.length}</span></h2></div></div>{alerts.length ? <div className="alert-list">{alerts.map((a) => <article className="alert-row" key={a.id}><span className="alert-glyph"><Bell size={17}/></span><div><span className="eyebrow">{a.severity} · {a.subject_ref || 'Farm'}</span><strong>{a.problem}</strong><small>{a.created_at}</small></div><ActionButton variant="quiet" disabled={busyId === a.id} onClick={() => void acknowledge(a.id)}>{busyId === a.id ? 'Saving…' : 'Acknowledge'}</ActionButton></article>)}</div> : <EmptyState title="No active alerts" detail="The current alert feed contains no active items."/>}</section><section className="queue-section"><div className="section-heading"><div><span className="eyebrow">EXPERT ESCALATION</span><h2>Consultations <span className="count-badge">{consultations.length}</span></h2></div></div><ExpertOnlyNote/>{consultations.length ? <div className="consultation-list">{consultations.map((c) => <article className="panel consultation" key={c.id}><div className="consultation-heading"><span className="severity-tag">{c.severity}</span><span className="muted">{c.source_agent} · {c.requested_at}</span></div><h3>{c.problem}</h3>{c.escalation_reason && <p>{c.escalation_reason}</p>}<details><summary>Resolve consultation</summary><form className="form-stack" onSubmit={(e) => void resolve(e, c.id)}><Field name="expert_name" label="Expert name" required/><TextAreaField name="notes" label="Resolution notes" required/><ActionButton type="submit" busy={busyId === c.id}>Submit resolution</ActionButton></form></details></article>)}</div> : <EmptyState title="No pending consultations" detail="No expert escalations are waiting for a response."/>}</section></>}</div>;
}
