import { ImagePlus, LocateFixed, ScanLine } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { api } from '../api/client';
import { useApp } from '../context/AppContext';
import type { Recommendation } from '../types';
import { ActionButton, apiError, FarmRequired, Field, PageHeader, SelectField, WorkflowResult } from '../components/Ui';

export function ScanPage({ kind }: { kind: 'crop' | 'livestock' }) {
  const { farmId } = useApp();
  const [ref, setRef] = useState(''); const [crop, setCrop] = useState(''); const [species, setSpecies] = useState('cattle');
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState(''); const [result, setResult] = useState<Recommendation | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!file) { setPreview(''); return; } const url = URL.createObjectURL(file); setPreview(url); return () => URL.revokeObjectURL(url); }, [file]);
  async function submit(event?: FormEvent) {
    event?.preventDefault(); if (!farmId || !file || !ref.trim()) return;
    setBusy(true); setError(''); setResult(null);
    try { setResult(kind === 'crop' ? await api.cropScan(farmId, ref.trim(), crop, file) : await api.livestockScan(farmId, ref.trim(), species, file)); }
    catch (e) { setError(apiError(e)); } finally { setBusy(false); }
  }
  return <div className="page-wrap"><PageHeader eyebrow="PERCEPTION / IMAGE ANALYSIS" title={kind === 'crop' ? 'Crop scan' : 'Livestock scan'} description={kind === 'crop' ? 'A visual screen to help decide what deserves a closer look.' : 'Record a visual observation and receive a structured risk screen.'} action={<span className="stage-indicator"><ScanLine size={16}/> INPUT <i/> ANALYSIS <i/> ACTION</span>}/>
    <div className="scan-layout"><section className="panel scan-panel"><div className="panel-heading"><div><span className="eyebrow">01 · Provide context</span><h2>{kind === 'crop' ? 'What are we looking at?' : 'Identify the animal'}</h2></div><span className="panel-icon"><ImagePlus size={17}/></span></div><FarmRequired/>
      <form className="form-stack" onSubmit={submit}>
        <Field label={kind === 'crop' ? 'Field reference' : 'Animal reference'} value={ref} onChange={(e) => setRef(e.target.value)} required placeholder={kind === 'crop' ? 'e.g. North field' : 'e.g. Cow 07'}/>
        {kind === 'crop' ? <Field label="Crop" value={crop} onChange={(e) => setCrop(e.target.value)} required placeholder="e.g. tomato"/> : <SelectField label="Species" value={species} onChange={(e) => setSpecies(e.target.value)}><option value="cattle">Cattle</option><option value="buffalo">Buffalo</option><option value="goat">Goat</option><option value="sheep">Sheep</option><option value="other">Other</option></SelectField>}
        <label className="upload-zone" htmlFor="scan-image"><input id="scan-image" type="file" accept="image/*" capture="environment" onChange={(e) => setFile(e.target.files?.[0] || null)} required/><span className="upload-art"><ImagePlus size={22}/></span><strong>{file ? file.name : 'Add a clear image'}</strong><small>{file ? `${(file.size / 1024 / 1024).toFixed(1)} MB · Select to replace` : 'Take a photo or choose a file'}</small></label>
        {preview && <img className="image-preview" src={preview} alt="Selected scan preview"/>}
        <ActionButton type="submit" busy={busy} disabled={!farmId || !file || !ref.trim()}>{busy ? 'Analyzing image' : 'Analyze image'}</ActionButton>
      </form>
      <div className="scan-disclaimer">This visual screen is an aid, not a substitute for an in-person agricultural or veterinary assessment.</div>
    </section><div className="scan-output"><div className="eyebrow">02 · RESULT</div>{busy ? <WorkflowResult result={null} error="" loading/> : error ? <WorkflowResult result={null} error={error} loading={false} onRetry={() => void submit()}/> : result ? <WorkflowResult result={result} error="" loading={false}/> : <div className="result-placeholder"><div className="result-rings"><span/><span/><ScanLine size={21}/></div><strong>Evidence will appear here</strong><p>Submit an image to begin. Aranya will show the backend’s findings, confidence, and recommended next step.</p></div>}</div></div>
  </div>;
}

export function WeatherPage() {
  const { farmId } = useApp(); const [lat, setLat] = useState(''); const [lng, setLng] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [result, setResult] = useState<Recommendation | null>(null);
  function locate() { if (!navigator.geolocation) { setError('Location is not available in this browser.'); return; } navigator.geolocation.getCurrentPosition((p) => { setLat(String(p.coords.latitude)); setLng(String(p.coords.longitude)); setError(''); }, (e) => setError(`Could not get your location: ${e.message}`), { enableHighAccuracy: false, timeout: 10000 }); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!farmId) return; setBusy(true); setError(''); setResult(null); try { setResult(await api.weather(farmId, Number(lat), Number(lng))); } catch (e) { setError(apiError(e)); } finally { setBusy(false); } }
  return <div className="page-wrap"><PageHeader eyebrow="PERCEPTION / ENVIRONMENT" title="Weather risk" description="Request a forecast-based agricultural risk screen for a location."/><div className="workflow-grid"><section className="panel"><span className="eyebrow">Location context</span><h2>Where is the farm?</h2><FarmRequired/><form onSubmit={submit} className="form-stack"><div className="field-pair"><Field label="Latitude" type="number" step="any" value={lat} onChange={(e) => setLat(e.target.value)} required/><Field label="Longitude" type="number" step="any" value={lng} onChange={(e) => setLng(e.target.value)} required/></div><ActionButton type="button" variant="secondary" onClick={locate}><LocateFixed size={16}/> Use current location</ActionButton><small className="privacy-note">Location is used for this forecast request. It is not saved by this interface.</small><ActionButton type="submit" busy={busy} disabled={!farmId}>Check weather</ActionButton></form></section><section className="workflow-output"><div className="eyebrow">Analysis</div><WorkflowResult result={result} error={error} loading={busy} onRetry={() => { const form = document.querySelector<HTMLFormElement>('.workflow-grid form'); form?.requestSubmit(); }}/></section></div></div>;
}

export function SoilPage() {
  const { farmId } = useApp(); const [result, setResult] = useState<Recommendation | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!farmId) return; const f = new FormData(event.currentTarget); const fields: Record<string, unknown> = Object.fromEntries(f.entries()); for (const k of ['ph','nitrogen_ppm','phosphorus_ppm','potassium_ppm']) fields[k] = fields[k] !== '' ? Number(fields[k]) : null; if (!['ph','nitrogen_ppm','phosphorus_ppm','potassium_ppm'].some((k) => fields[k] !== null)) { setError('Enter at least one measurement.'); return; } setBusy(true); setError(''); setResult(null); try { setResult(await api.soil(farmId, fields)); } catch (e) { setError(apiError(e)); } finally { setBusy(false); } }
  return <div className="page-wrap"><PageHeader eyebrow="PERCEPTION / SOIL" title="Soil assessment" description="Share available measurements; partial readings are accepted and remain clearly scoped."/><div className="workflow-grid"><section className="panel"><span className="eyebrow">Field measurements</span><h2>What do you know?</h2><FarmRequired/><form onSubmit={submit} className="form-stack"><Field name="field_ref" label="Field reference" required placeholder="e.g. North field"/><Field name="crop_name" label="Crop" required placeholder="e.g. tomato"/><div className="field-pair"><Field name="ph" label="pH" type="number" min="0" max="14" step="0.1" placeholder="Optional"/><Field name="nitrogen_ppm" label="Nitrogen (ppm)" type="number" step="any" placeholder="Optional"/><Field name="phosphorus_ppm" label="Phosphorus (ppm)" type="number" step="any" placeholder="Optional"/><Field name="potassium_ppm" label="Potassium (ppm)" type="number" step="any" placeholder="Optional"/></div><SelectField name="source" label="Measurement source"><option value="farmer_reported">Farmer reported</option><option value="lab_report">Lab report</option><option value="estimated">Estimated</option></SelectField><ActionButton type="submit" busy={busy} disabled={!farmId}>Evaluate measurements</ActionButton></form></section><section className="workflow-output"><div className="eyebrow">Recommendation</div><WorkflowResult result={result} error={error} loading={busy} onRetry={() => document.querySelector<HTMLFormElement>('.workflow-grid form')?.requestSubmit()}/></section></div></div>;
}
